### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by nkraja1** [ARCyber123/ARCyber123.github.io#1]
In your website you state that Linux is not as susceptible to hacks due to it not being widely used. I would argue that linux is actually the most widely used OS on the planet. It's an OS that is used by many major websites and companies and is secure because the kernel is always being changed, adjusted and fixed. Android itself is a version of Linux and is the most widely used mobile OS. Google, Youtube, Facebook, Netflix and more are all using the Linux kernel. I agree that it is not widely used as an operating system for personal use due to issues like compatibily as you said. Great website, keep it up!

**Comment by ARCyber123** [comment]
Hello :) thanks to let me know that android is based on Linux. But on my website, I was referring to desktop OSes (by the way, did you join GitHub now?)

**Comment by nkraja1** [comment]
I joined github in 2018.

**Comment by ARCyber123** [comment]
Hi
I’ve mentioned “desktop operating system” in the latest commit now

**Comment by ARCyber123** [comment]
> I joined github in 2018.

You did? I don’t see any repositories! Are they all private?

**Comment by nkraja1** [comment]
Yes they are private. I had just been experimenting with web development and konami codes. I have the github student developer pack.

**Comment by ARCyber123** [comment]
Oh ok!

**Comment by ARCyber123** [comment]
So what codes are you writing?

**Comment by ARCyber123** [comment]
Do you have any collaborators?

**Comment by nkraja1** [comment]
I have not done much. I was just using github to mess with hosting of an html and css documents combined with netlify and dns records. I also use it to view repositories from youtube videos.

**Comment by ARCyber123** [comment]
Ok

**Comment by ARCyber123** [comment]
Hi! Do you want to be a collaborator?

**Comment by nkraja1** [comment]
Not at the moment but I will contact you if I change my mind.

**Comment by ARCyber123** [comment]
Ok

**Comment by nkraja1** [comment]
Did you make this website so it can be viewed by people or just to experiment with web development?

**Comment by ARCyber123** [comment]
Both lol

**Comment by nkraja1** [comment]
Oh, well then you must research more about SEO if you want it to be ranked on google and you must think about domains.

**Comment by ARCyber123** [comment]
Yes, but I don’t want to buy a domain...

**Comment by nkraja1** [comment]
There are MANY free domain registeries like freenom.

**Comment by ARCyber123** [comment]
Oh! Thanks!

**Comment by nkraja1** [comment]
If you want to get a premium domain for free I suggest getting the github student developer pack which gives two premium and expensive domains for free for the first year. You may need to use this link if you do not have a school issued email: https://github.blog/2019-07-30-how-to-get-the-github-student-developer-pack-without-a-student-id/

**Comment by ARCyber123** [comment]
Do I need to pay later?

**Comment by ARCyber123** [comment]
> There are MANY free domain registeries like freenom.

I forgot about this..

**Comment by nkraja1** [comment]
You do not need to pay later as it does not require any form of payment information apon registering.

**Comment by ARCyber123** [comment]
Ok then

**Comment by nkraja1** [comment]
If you want to extend the domain by more than the allotted one year you will have to pay but it is not necessary when you are just starting out.
